# Generated by Django 6.0 on 2025-12-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_repo', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'private'), (1, 'public'), (2, 'beta'), (3, 'done'), (4, 'archived')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
